from src.processar_dados_faturamento import processar_dados_faturamento
from src.processar_dados_mais_vendidos import processar_dados_mais_vendidos

# Processar os dados
processar_dados_faturamento()
processar_dados_mais_vendidos()
